openapi: 3.0.0
info:
  title: "Family Budget REST API"
  description: "Sample API"
  version: "0.0.1"

servers:
  - url: "/api"

paths:
  /account:
    get:
      operationId: "account.get_all"
      responses:
        "200":
          description: "Successfully read accounts list"
  
  /account/try_login:
    post:
      operationId: "account.try_login"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "body"
              type: "object"
              properties:
                username:
                  type: "string"
                passwdhash:
                  type: "string"
      responses:
        "200":
          description: "Login permitted"
        "401":
          description: "Wrong login credentials"

  /account/try_create_account:
    post:
      operationId: "account.try_create_account"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "body"
              type: "object"
              properties:
                username:
                  type: "string"
                passwdhash:
                  type: "string"
      responses:
        "200":
          description: "User created"
        "400":
          description: "User already exists"

  /budget/{user_id}:
    get:
      operationId: "budget.get_by_user"
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
          required: true
      responses:
        "200":
          description: "List of all budgets available for a user"